### PR TITLE
Made a README for easy understanding about the project for a new user

### PR DESCRIPTION
**Pull request by vishalsingh2972**

### CODE REVIEW

**Comment by xenedium** [comment]
Hello @vishalsingh2972 , Thank you for your efforts and contributions, we'll be glad to merge however there are some small things that need to be changed if you are willing to:
- In the Installation section: After navigation to the project directory, there are some services that need to be running in order for the app to work locally, these services are in the ```docker-compose.yml``` file, If you can update the the Installation section and add this it would be great !
```bash
# Docker required
docker-compose up -d
# Or
docker compose up -d
```
-  In the Technologies section: We are currently not using ```Thymeleaf & Bootstrap```, for our frontend we'll be using React a long with a UI library that is yet to be determined, here is the repository: [https://github.com/DaddaAdam/Spring-Reddit-Frontend](https://github.com/DaddaAdam/Spring-Reddit-Frontend). As for the DBMS we are using ```MySQL``` not ```PostgreSQL```

**Comment by xenedium** [comment]
@vishalsingh2972 You are also welcomed to innovate !

**Comment by vishalsingh2972** [comment]
> Hello @vishalsingh2972 , Thank you for your efforts and contributions, we'll be glad to merge however there are some small things that need to be changed if you are willing to:
> 
> * In the Installation section: After navigation to the project directory, there are some services that need to be running in order for the app to work locally, these services are in the `docker-compose.yml` file, If you can update the the Installation section and add this it would be great !
> 
> ```shell
> # Docker required
> docker-compose up -d
> # Or
> docker compose up -d
> ```
> 
> * In the Technologies section: We are currently not using `Thymeleaf & Bootstrap`, for our frontend we'll be using React a long with a UI library that is yet to be determined, here is the repository: https://github.com/DaddaAdam/Spring-Reddit-Frontend. As for the DBMS we are using `MySQL` not `PostgreSQL`

@xenedium have made the changes you requested, please check and merge the PR https://github.com/DaddaAdam/Spring-Reddit/pull/12

**Comment by vishalsingh2972** [comment]
> Hello @vishalsingh2972 , Thank you for your efforts and contributions, we'll be glad to merge however there are some small things that need to be changed if you are willing to:
> 
> * In the Installation section: After navigation to the project directory, there are some services that need to be running in order for the app to work locally, these services are in the `docker-compose.yml` file, If you can update the the Installation section and add this it would be great !
> 
> ```shell
> # Docker required
> docker-compose up -d
> # Or
> docker compose up -d
> ```
> 
> * In the Technologies section: We are currently not using `Thymeleaf & Bootstrap`, for our frontend we'll be using React a long with a UI library that is yet to be determined, here is the repository: https://github.com/DaddaAdam/Spring-Reddit-Frontend. As for the DBMS we are using `MySQL` not `PostgreSQL`

@xenedium have made the changes you requested, please check and merge the PR https://github.com/DaddaAdam/Spring-Reddit/pull/12

**Pull request merged**
